version: '2.4'
services:
  db:
    image: mysql/mysql-server:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    mem_limit: 300M
  adminer:
      image: adminer
      restart: always
      ports:
        - 5080:8080
  mongo:
    image: mongo:3.2-jessie
    restart: always
    mem_limit: 300M
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

